# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bf9b89c885ab80036eb4c69afc30bcc433e65ceb0308771747084d09b6088439c0ca493503f4131ea4edb9c8fa9d5f372f53beadf3119ebd1f7899f69bffa28

test:
  secret_key_base: fb14086966cb04fb8988463be2409706ea8776c1ac3ebbaed8fb6cf8b93c0b8fecc9569b926e316b42a70cf77e56d5a9e615ab46ba4b51972d732eb2d9cf48eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
